sudo: required

services:
  - docker

before_install:
  - docker build -t bebetaro/test_frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true bebetaro/test_frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-767139879868"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

